name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build - ${{ matrix.platform.os }}
    runs-on: ${{ matrix.platform.runs-on }}
    strategy:
      matrix:
        platform:
          - os: linux-x86_64
            runs-on: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin: urchin
          - os: macos-x86_64
            runs-on: macos-latest
            target: x86_64-apple-darwin
            bin: urchin
          - os: macos-aarch64
            runs-on: macos-latest
            target: aarch64-apple-darwin
            bin: urchin

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.target }}

      - name: Build binary
        run: cargo build --release --bin urchin --target ${{ matrix.platform.target }}

      - name: Archive binary
        run: |
          cd target/${{ matrix.platform.target }}/release
          tar czf ../../../urchin-${{ matrix.platform.os }}.tar.gz urchin
          cd -

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: urchin-${{ matrix.platform.os }}
          path: urchin-${{ matrix.platform.os }}.tar.gz

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*.tar.gz
          generate_release_notes: true
          draft: false
          prerelease: false
